export enum GlobalMarket {
  NORTH_AMERICA = 'NORTH AMERICA',
  EUROPE= 'EUROPE',
  ASIA_PACIFIC = 'ASIA PACIFIC',
  SOUTH_AMERICA = 'SOUTH AMERICA',
  AFRICA = 'AFRICA',
  MIDDLE_EAST = 'MIDDLE EAST',
}